"""
bulk_update_response automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Union
from .record import Record
class BulkUpdateResponse(BaseModel):
    created_records: Optional[List[str]] = Field(default=None, alias="createdRecords")
    updated_records: Optional[List[str]] = Field(default=None, alias="updatedRecords")
    records: Optional[List[Record]] = Field(default=None, alias="records")
    pass
