"""
Client automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

import requests
import sdkgen
from requests import RequestException
from typing import List

from .meta_tag import MetaTag
from .records_tag import RecordsTag
from .fields_tag import FieldsTag
from .tables_tag import TablesTag
from .comments_tag import CommentsTag

class Client(sdkgen.ClientAbstract):
    def __init__(self, base_url: str, credentials: sdkgen.CredentialsInterface):
        super().__init__(base_url, credentials)

    def meta(self) -> MetaTag:
        return MetaTag(
            self.http_client,
            self.parser
        )

    def records(self) -> RecordsTag:
        return RecordsTag(
            self.http_client,
            self.parser
        )

    def fields(self) -> FieldsTag:
        return FieldsTag(
            self.http_client,
            self.parser
        )

    def tables(self) -> TablesTag:
        return TablesTag(
            self.http_client,
            self.parser
        )

    def comments(self) -> CommentsTag:
        return CommentsTag(
            self.http_client,
            self.parser
        )



    @staticmethod
    def build(token: str):
        return Client("https://api.airtable.com/", sdkgen.HttpBearer(token))

