"""
comment automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Union
from .comment_author import CommentAuthor
class Comment(BaseModel):
    id: Optional[str] = Field(default=None, alias="id")
    created_time: Optional[str] = Field(default=None, alias="createdTime")
    last_updated_time: Optional[str] = Field(default=None, alias="lastUpdatedTime")
    text: Optional[str] = Field(default=None, alias="text")
    parent_comment_id: Optional[str] = Field(default=None, alias="parentCommentId")
    reactions: Optional[str] = Field(default=None, alias="reactions")
    author: Optional[CommentAuthor] = Field(default=None, alias="author")
    pass
