"""
field automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Union
from .field_options import FieldOptions
class Field(BaseModel):
    id: Optional[str] = Field(default=None, alias="id")
    type: Optional[str] = Field(default=None, alias="type")
    name: Optional[str] = Field(default=None, alias="name")
    description: Optional[str] = Field(default=None, alias="description")
    options: Optional[FieldOptions] = Field(default=None, alias="options")
    pass
