"""
table automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Union
from .field import Field
class Table(BaseModel):
    id: Optional[str] = Field(default=None, alias="id")
    primary_field_id: Optional[str] = Field(default=None, alias="primaryFieldId")
    name: Optional[str] = Field(default=None, alias="name")
    description: Optional[str] = Field(default=None, alias="description")
    fields: Optional[List[Field]] = Field(default=None, alias="fields")
    pass
