"""
record_collection automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Union
from .record import Record
class RecordCollection(BaseModel):
    offset: Optional[str] = Field(default=None, alias="offset")
    records: Optional[List[Record]] = Field(default=None, alias="records")
    pass
